### ISSUE TITLE
BUG: hidden error message

### ISSUE THREAD

**Issue by big-vl** [karolyi/py3-validate-email#30] opened 2020-09-30 15:35 UTC
i dont want to see error messages in the console, i only want to receive True and False, how to do this? I set debug=False

**Comment by karolyi** [comment] 2020-09-30 15:37
In order for me to be able to answer your question, post the logs it's emitting please.

**Comment by big-vl** [comment] 2020-09-30 22:03
............Validation for '' failed: Invalid email address.
.Validation for '' failed: Invalid email address.
......Validation for '' failed: Invalid email address.
..Validation for '' failed: Invalid email address.
.

**Comment by big-vl** [comment] 2020-09-30 22:07
I wrote tests during registration so that registration would not take place, respectively, he says that the email is empty, the test is completed successfully, since it cannot register as planned by the tests, but I do not need such messages in tests, how to disable it?

**Comment by karolyi** [comment] 2020-10-01 10:00
Do you use any of python's logging module in your code? This project uses the same framework (just like django does), and so if you do, you can set up logging filters to filter out this module's messages.

**Comment by karolyi** [comment] 2020-10-01 10:12
Also, passing an empty email address will result in failure, of course.

**Comment by big-vl** [comment] 2020-10-01 15:40
I use this in tests, do you suggest that I disable the logging log in tests?
I run the tests with the command:
python3 -m unittest -v
your suggestions? I have 300 test files.

**Comment by karolyi** [comment] 2020-10-01 15:51
you can construct a test runner with disabling logging, something like [the opposite of how to post debug logs](https://github.com/karolyi/py3-validate-email#my-email-doesnt-check-out).

**Comment by big-vl** [comment] 2020-10-01 21:56
I understood in which direction to look, but then I will not see the prints I need, I already understood this, everything is very bad, it's a pity that I will have to use a modified version of your module to easily disable logs, because of one message

**Comment by karolyi** [comment] 2020-10-03 12:13
logging ≠ debug.

What you want here is to remove logging entirely by turning off the debug option. Logging is for generic information about the validated addresses. I will look into what's doable, but wanted to clarify this.

**Comment by big-vl** [comment] 2020-10-03 12:22
if I disable then I don't see the information I need, it intersects with logging, why don't you make it easier, your module is the best, but I would like to disable logging in your module

**Comment by karolyi** [comment] 2020-10-04 10:40
Closing this as wontfix.

With a little bit of searching and learning, you can find yourself a way to filter out your unwanted messages from logging. I just did it locally for testing.

Coming here and complaining about how it's not doing what you want is not a bug, it's you not wanting to put in the work and research it.

**Closed by karolyi** 2020-10-04 10:40 UTC
